import http from 'node:http';
import {readFile} from 'node:fs/promises';
const port=Number(process.env.PORT??19631);
const previewLanguage=process.env.PREVIEW_LANGUAGE??'zh-CN';
const initial={phase:'stopped',busy:false,error:'',upstream:'2.9.0',language:previewLanguage,localUrl:null,addresses:[],certificate:process.env.PREVIEW_CERTIFICATE==='1'?{fingerprint:'Preview SHA256 fingerprint'}:null,config:{enabled:false,httpEnabled:false,httpsEnabled:true,httpPort:19627,httpsPort:19628,interfaces:null,language:'auto',systemLanguage:previewLanguage,username:'',configured:false},interfaces:[{key:'wlan0|preview',name:'wlan0',physical:true,up:true,enabled:true,addresses:[{address:'192.168.5.67',cidr:'192.168.5.67/24'}]},{key:'tun0|preview',name:'tun0',physical:false,up:true,enabled:false,addresses:[{address:'10.8.0.2',cidr:'10.8.0.2/24'}]}]};
const bootstrap=`const s=${JSON.stringify(initial)};window.__framelyBridge={subscribe:()=>()=>{},request:async(op,p={})=>{if(op==='language.get')return {preference:'auto',language:s.config.systemLanguage};if(op==='window.open'){window.open('/main','_blank');return true;}if(op==='window.close'){window.close();return true;}if(op!=='call')return true;const {method,params={}}=p;if(method==='certificate.export')return {path:'/home/steam/Downloads/frame-termix-preview.crt'};if(method==='credentials.set'){s.config.username=params.username;s.config.configured=true;}if(method==='settings.save')Object.assign(s.config,params);if(method==='language.sync'){s.config.systemLanguage=params.language;}if(method==='service.set'){s.config.enabled=params.enabled;s.phase=params.enabled?'running':'stopped';s.addresses=params.enabled?['https://192.168.5.67:'+s.config.httpsPort]:[];}s.language=s.config.language==='auto'?s.config.systemLanguage:s.config.language;return JSON.parse(JSON.stringify(s));}};`;
http.createServer(async(req,res)=>{
 try{
  if(req.url==='/quick'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html style="background:#17191c;color-scheme:dark"><body style="margin:0;background:#17191c"><iframe title="Framely quick panel preview" src="/plugin/quick" style="width:100%;height:100vh;border:0;display:block"></iframe></body></html>');return;}
  if(req.url==='/page.js'){res.setHeader('content-type','text/javascript');res.end(await readFile('payload/page.js'));return;}
  if(req.url==='/main'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<html><body style="background:#101820;color:#edf2fa;font:20px system-ui;padding:30px"><h1>Termix Web</h1><p>此预览只模拟快捷面板。完整 Web 服务由离线运行包提供。</p></body></html>');return;}
  res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><div id=root></div><script>'+bootstrap+'</script><script src=/page.js></script>');
 }catch(e){res.writeHead(500);res.end(e.message);}
}).listen(port,'127.0.0.1',()=>console.log(`Quick panel preview: http://127.0.0.1:${port}/quick (simulated data only)`));
